#!/usr/bin/python3

scanner = nmap.PortScanner()

ip_address = '172.96.178.218'
type (ip_address)
    
scannner.scan(ip_address, '443', '-v -sS -A -0')
print (scanner.scaninfo())
print ('IP Status: ', scanner[ip_address].state())
print (scanner[ip_address].all_protocols())
